{% set name = "yt-dlg" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yt_dlg-{{ version }}.tar.gz
  sha256: c8b5ce181eb7c678659ced228a061515eb5b85b920eb5e0239fe428da85779e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - yt-dlg = youtube_dl_gui.app:main

requirements:
  host:
    - pip
    - polib
    - pyinstaller
    - python >=3.7
  run:
    - polib >=1.1.0
    - pyinstaller <=5.6.2,>=3.6
    - pypubsub >=4.0.3
    - python >=3.7
    - wxpython <=4.1.2a1,>=4.0.7.post2

test:
  imports:
    - youtube_dl_gui
  commands:
    - pip check
    #Can't test yt-dlg entry-point since this is a graphic interface
  requires:
    - pip

about:
  home: https://oleksis.github.io/youtube-dl-gui/
  summary: Youtube Downloader GUI
  dev_url: https://github.com/oleksis/youtube-dl-gui/
  license: Unlicense
  license_file: LICENSE
  description: |
    A cross platform front-end GUI of the popular `youtube-dl` media downloader written in `wxPython`.

extra:
  recipe-maintainers:
    - HeavyTony2
